[{"testId":"r3","title":["Evaluation RCT-211-B120-E2","should have basic structure"],"state":"failed","body":"() => {\n      cy.visit(url);\n      cy.get(\"[data-testid=todo-input]\").should(\"be.visible\");\n      cy.get(\"[data-testid=add-button]\").should(\"be.visible\");\n      cy.then(() => {\n        acc_score += 1;\n      });\n    }","displayError":"TypeError: The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)","attempts":[{"state":"failed","error":{"name":"TypeError","message":"The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","stack":"    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)"},"timings":{"lifecycle":40,"before each":[{"hookId":"h1","fnDuration":1,"afterFnDuration":1},{"hookId":"h3","fnDuration":101,"afterFnDuration":0}],"test":{"fnDuration":2956,"afterFnDuration":726},"after each":[{"hookId":"h2","fnDuration":1,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2022-11-26T22:39:21.716Z","wallClockDuration":3838,"videoTimestamp":16480}]},{"testId":"r4","title":["Evaluation RCT-211-B120-E2","Should get initial todos by GET request"],"state":"failed","body":"() => {\n      cy.intercept(\"GET\", `${server_url}/todos`).as(\"getTodos\"); // cy.contains(\"h1\", /React Todo Crud Axios/i).should(\"be.visible\");\n\n      cy.visit(url);\n      cy.wait(\"@getTodos\");\n      cy.get('[data-testid=\"todos-wrapper\"]').children().should(\"have.length\", 5);\n      cy.then(() => {\n        acc_score += 2;\n      });\n    }","displayError":"TypeError: The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)","attempts":[{"state":"failed","error":{"name":"TypeError","message":"The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","stack":"    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)"},"timings":{"lifecycle":124,"before each":[{"hookId":"h1","fnDuration":0,"afterFnDuration":1},{"hookId":"h3","fnDuration":26,"afterFnDuration":0}],"test":{"fnDuration":1097,"afterFnDuration":390},"after each":[{"hookId":"h2","fnDuration":0,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2022-11-26T22:39:25.576Z","wallClockDuration":1654,"videoTimestamp":20340}]},{"testId":"r5","title":["Evaluation RCT-211-B120-E2","Check if user is able to add new task 1"],"state":"failed","body":"() => {\n      cy.visit(url);\n      cy.intercept(\"POST\", `${server_url}/todos`).as(\"postTodos\");\n      cy.get('[data-testid=\"todo-input\"]').type(\"New Task\");\n      cy.get('[data-testid=\"add-button\"]').click();\n      cy.wait(\"@postTodos\").then(() => {\n        cy.get('[data-testid=\"todos-wrapper\"]').children().should(\"have.length\", 6);\n        cy.get('[data-testid=\"todos-wrapper\"]').children().eq(5).contains(\"New Task\");\n        cy.get('[data-testid=\"todos-wrapper\"]').children().eq(5).contains(\"False\");\n      });\n      cy.then(() => {\n        acc_score += 3;\n      });\n    }","displayError":"TypeError: The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)","attempts":[{"state":"failed","error":{"name":"TypeError","message":"The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","stack":"    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)"},"timings":{"lifecycle":9,"before each":[{"hookId":"h1","fnDuration":0,"afterFnDuration":1},{"hookId":"h3","fnDuration":9,"afterFnDuration":0}],"test":{"fnDuration":1043,"afterFnDuration":1056},"after each":[{"hookId":"h2","fnDuration":0,"afterFnDuration":1}]},"failedFromHookId":null,"wallClockStartedAt":"2022-11-26T22:39:27.247Z","wallClockDuration":2125,"videoTimestamp":22011}]},{"testId":"r6","title":["Evaluation RCT-211-B120-E2","Check if user is able to add new task 2"],"state":"failed","body":"() => {\n      cy.visit(url);\n      cy.intercept(\"POST\", `${server_url}/todos`).as(\"postTodos\");\n      cy.get('[data-testid=\"todo-input\"]').type(\"Read Books\");\n      cy.get('[data-testid=\"add-button\"]').click();\n      cy.wait(\"@postTodos\").then(() => {\n        cy.get('[data-testid=\"todos-wrapper\"]').children().should(\"have.length\", 6);\n        cy.get('[data-testid=\"todos-wrapper\"]').children().eq(5).contains(\"Read Books\");\n        cy.get('[data-testid=\"todos-wrapper\"]').children().eq(5).contains(\"False\");\n      });\n      cy.then(() => {\n        acc_score += 3;\n      });\n    }","displayError":"TypeError: The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)","attempts":[{"state":"failed","error":{"name":"TypeError","message":"The following error originated from your application code, not from Cypress.\n\n  > dispatch is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","stack":"    at getTodos (http://localhost:3000/static/js/bundle.js:342:3)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:107:60)\n    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:46063:30)\n    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:47556:17)\n    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:47528:13)\n    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:47518:11)\n    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:47508:7)\n    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:49393:7)\n    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:49345:18)\n    at <unknown> (http://localhost:3000/static/js/bundle.js:49160:13)"},"timings":{"lifecycle":11,"before each":[{"hookId":"h1","fnDuration":1,"afterFnDuration":0},{"hookId":"h3","fnDuration":5,"afterFnDuration":1}],"test":{"fnDuration":1309,"afterFnDuration":1407},"after each":[{"hookId":"h2","fnDuration":0,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2022-11-26T22:39:29.403Z","wallClockDuration":2741,"videoTimestamp":24167}]},{"testId":"r7","title":["Evaluation RCT-211-B120-E2","generate score"],"state":"passed","body":"() => {\n      console.log(\"final score:\", acc_score); ////////////// this should not be changed\n\n      let result = {\n        id,\n        marks: Math.ceil(acc_score)\n      };\n      result = JSON.stringify(result);\n      cy.writeFile(\"results.json\", `\\n${result},`, {\n        flag: \"a+\"\n      }, err => {\n        if (err) {\n          console.error(err);\n        }\n      }); //////////////////\n    }","displayError":null,"attempts":[{"state":"passed","error":null,"timings":{"lifecycle":14,"before each":[{"hookId":"h1","fnDuration":0,"afterFnDuration":2},{"hookId":"h3","fnDuration":7,"afterFnDuration":1}],"test":{"fnDuration":7,"afterFnDuration":1},"after each":[{"hookId":"h2","fnDuration":0,"afterFnDuration":0}]},"failedFromHookId":null,"wallClockStartedAt":"2022-11-26T22:39:32.160Z","wallClockDuration":44,"videoTimestamp":26924}]}]